/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.production.example.jsonc --include-runtime=false --strict-vars=false worker-configuration.production.d.ts` (hash: 05e167bd33977f7beb2d90ba83c51466)
interface __BaseEnv_Env {
	MAP_BUCKET: R2Bucket;
	DB: D1Database;
	VALIDATION_QUEUE: Queue;
	AUTH_RATE_LIMITER: RateLimit;
	API_RATE_LIMITER: RateLimit;
	DOWNLOAD_RATE_LIMITER: RateLimit;
	ENVIRONMENT: string;
	ALLOW_MOCK_AUTH: string;
	AUTH_ISSUER: string;
	AUTH_AUDIENCE: string;
	MOCK_STEAM_ID64: string;
	PUBLIC_ORIGIN: string;
	UPLOAD_DAILY_LIMIT: string;
	UPLOAD_DAILY_BYTES: string;
	RETAINED_BYTES_PER_ACCOUNT: string;
	MAPS_PER_ACCOUNT_LIMIT: string;
	MAINTAINER_STEAM_IDS: string;
	AUTH_SIGNING_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
