/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: ae53f7391bce657e7e324dc05bee764c)
interface __BaseEnv_Env {
	MAP_BUCKET: R2Bucket;
	DB: D1Database;
	VALIDATION_QUEUE: Queue;
	AUTH_RATE_LIMITER: RateLimit;
	API_RATE_LIMITER: RateLimit;
	DOWNLOAD_RATE_LIMITER: RateLimit;
	ENVIRONMENT: string;
	ALLOW_MOCK_AUTH: string;
	AUTH_ISSUER: string;
	AUTH_AUDIENCE: string;
	MOCK_STEAM_ID64: string;
	PUBLIC_ORIGIN: string;
	DOWNLOAD_DAILY_BYTES: string;
	DOWNLOAD_CONCURRENCY: string;
	PUBLISHER_STEAM_IDS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
